server:
 port: 8007
spring:
 profiles:
  active: user
 datasource:
  url: jdbc:mysql://localhost:3306/capstone
  username: root
  password: 2002
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  hibernate.ddl-auto: update
  show-sql: true
  properties: 
   hibernate:
    format_sql: true

mesg: This is default Profile

 
 
    
